## MANAGED BY TERRAFORM - MANUALLY EDIT ONLY IN https://github.com/areionsec/infrastructure/blob/master/modules/default-repository/managed_files_repo_root/.github/pr-lint.yml
projects:
  - 'APP'
  - 'ARC'
  - 'BUG'
  - 'COD'
  - 'DEL'
  - 'ENR'
  - 'FIN'
  - 'FR'
  - 'IDEA'
  - 'IN'
  - 'ING'
  - 'INBUG'
  - 'PI'
  - 'PL'
  - 'POL'
  - 'POV'
  - 'PRO'
  - 'PS'
  - 'REM'
  - 'SOL'
  - 'TA'
  - 'TEA'
check_title: true
check_branch: false
check_commits: false
