## MANAGED BY TERRAFORM - MANUALLY EDIT ONLY IN
## https://github.com/areionsec/terraform-aws-areion-components/blob/master/modules/resource-wrapper_github_repository/templates/managed_files_repo_root/dot_github/pr-lint.yml
projects:
  - APP
  - ARC
  - BUG
  - COD
  - DEL
  - ENR
  - FIN
  - FR
  - IDEA
  - IN
  - INBUG
  - ING
  - PI
  - PL
  - POL
  - POV
  - PRO
  - PS
  - REM
  - RES
  - SOL
  - TA
  - TEA
  - WM
  - INTEG
  - DBG
check_title: true
check_branch: false
check_commits: false
